// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mngTp1tomany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mngTp1tomany));
        
        string IMigrationMetadata.Id
        {
            get { return "202401011752527_mngTp1tomany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
